export default {
  SCROLL_TO_BOTTOM: 'SCROLL_TO_BOTTOM',
  SCROLL_TO_SD: 'SCROLL_TO_SD',
  SCROLL_LEAVE_SD: 'SCROLL_LEAVE_SD',
  SCROLL_TO_DROP: 'SCROLL_TO_DROP',
  MOBILE_DEVICE: 'MOBILE_DEVICE',
  DESKTOP_DEVICE: 'DESKTOP_DEVICE',
  OPEN_LAYER: 'OPEN_LAYER',
  CLOSE_LAYER: 'CLOSE_LAYER',
  LOADING_SERVER_DATA: 'LOADING_SERVER_DATA',
  SERVER_TIMEOUT: 'SERVER_TIMEOUT',
  SERVER_FAIL: 'SERVER_FAIL',
  GET_SERVER_NO_DATA: 'GET_SERVER_NO_DATA',
  GET_SERVER_MOBILE_DATA: 'GET_SERVER_MOBILE_DATA',
  GET_SERVER_MOBILE_NO_DATA: 'GET_SERVER_MOBILE_NO_DATA',
  GET_SERVER_DATA: 'GET_SERVER_DATA',
  GET_SERVER_MOBILE_ALL_DATA: 'GET_SERVER_MOBILE_ALL_DATA'
};

